version : '3.9'

services:
 fastapi:
    build:
      context: ./python/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./code/:/app/
    ports:
      - "8000:8000"
    networks: 
        - data-network

networks:
  data-network:
    driver: bridge